# Generated by Django 3.0.6 on 2020-06-05 09:40

from django.db import migrations, models
import generaltables.models


class Migration(migrations.Migration):

    dependencies = [
        ('generaltables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tester',
            options={'ordering': ['last_name', 'first_name', 'middle_name'], 'verbose_name': 'Испытатель', 'verbose_name_plural': 'Испытатели'},
        ),
        migrations.AlterModelOptions(
            name='testobject',
            options={'ordering': ['title_object'], 'verbose_name': 'Объект испытания', 'verbose_name_plural': 'Объeкты испытания'},
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.FileField(help_text="Разрешенные типы файлов: 'rar', 'pdf', 'doc', 'txt' и т.д.", max_length=150, upload_to=generaltables.models.content_report_name, validators=[generaltables.models.validate_report_extension], verbose_name='Файл'),
        ),
    ]
