# Generated by Django 3.0.6 on 2020-05-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generaltables', '0001_initial'),
        ('calculatedtrials', '0003_auto_20200531_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculated',
            name='testers',
            field=models.ManyToManyField(related_name='calculateds', to='generaltables.Tester', verbose_name='Испытатель'),
        ),
    ]
