# Generated by Django 3.0.6 on 2020-05-31 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_experimental', models.CharField(db_index=True, max_length=250, verbose_name='Цель экспериментального испытания')),
                ('slug_experimental', models.SlugField(blank=True, max_length=250, unique=True)),
                ('data_experimental', models.DateField(db_index=True, verbose_name='Дата экспериментального испытания')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimentals_1', to='stands.Stand', verbose_name='Стенд')),
            ],
            options={
                'verbose_name': 'Экспериментальное испытание',
                'verbose_name_plural': 'Экспериментальные испытания',
            },
        ),
    ]
