# Generated by Django 3.0.6 on 2020-05-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generaltables', '0001_initial'),
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimental',
            name='testers',
            field=models.ManyToManyField(related_name='experimentals_tester', to='generaltables.Tester', verbose_name='Испытатель'),
        ),
    ]
