# Generated by Django 3.0.6 on 2020-06-06 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculatedtrials', '0005_auto_20200605_0940'),
        ('trials', '0005_auto_20200605_0940'),
        ('generaltables', '0002_auto_20200605_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_calculated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_calculated', to='calculatedtrials.Calculated', verbose_name='Расчетное испытание'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_experimental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_experimental', to='trials.Experimental', verbose_name='Экспериментальное испытание'),
        ),
    ]
