# Generated by Django 3.0.6 on 2020-05-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generaltables', '0001_initial'),
        ('trials', '0002_experimental_testers'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimental',
            name='testobjects',
            field=models.ManyToManyField(related_name='objects_experimental', to='generaltables.TestObject', verbose_name='Объект испытания'),
        ),
    ]
