# Generated by Django 3.0.6 on 2020-06-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0004_auto_20200601_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimental',
            name='data_experimental',
            field=models.DateField(db_index=True, help_text='Введите дату по данному формату: <em>DD.MM.YYYY</em>', verbose_name='Дата экспериментального испытания'),
        ),
    ]
