# Generated by Django 3.0.6 on 2020-05-31 21:06

import calculatedtrials.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_calculated', models.CharField(db_index=True, max_length=250, verbose_name='Цель расчетного испытания')),
                ('slug_calculated', models.SlugField(blank=True, max_length=250, unique=True)),
                ('data_calculated', models.DateField(db_index=True, verbose_name='Дата расчетного испытания')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculateds', to='stands.Stand', verbose_name='Стенд')),
            ],
            options={
                'verbose_name': 'Расчетное испытание',
                'verbose_name_plural': 'Расчетные испытания',
            },
        ),
        migrations.CreateModel(
            name='SettlementFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_settlementfile', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Название расчетного файла')),
                ('settlementfile', models.FileField(help_text="Недопустимые типы файлов: 'png', 'jpg', 'jpeg', 'gif', 'svg'", max_length=150, upload_to='calculatedtrials/', validators=[calculatedtrials.models.validate_report_extension], verbose_name='Расчетный файл')),
                ('settlementfile_calculated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlementfiles', to='calculatedtrials.Calculated', verbose_name='Расчетное испытание')),
            ],
            options={
                'verbose_name': 'Расчетный файл',
                'verbose_name_plural': 'Расчетные файлы',
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_graph', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Название графика')),
                ('graph', models.ImageField(help_text="Разрешенные типы файлов: 'png', 'jpg', 'jpeg', 'gif', 'svg'", max_length=150, upload_to='calculatedtrials/', verbose_name='График')),
                ('graph_calculated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='calculatedtrials.Calculated', verbose_name='Расчетное испытание')),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики',
            },
        ),
    ]
