# Generated by Django 3.0.6 on 2020-05-31 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generaltables', '0001_initial'),
        ('calculatedtrials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculated',
            name='testobject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='object_calculated', to='generaltables.TestObject', verbose_name='Объект испытания'),
        ),
    ]
