# Generated by Django 3.0.6 on 2020-05-31 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generaltables', '0001_initial'),
        ('calculatedtrials', '0002_calculated_testobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculated',
            name='testobject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_calculated', to='generaltables.TestObject', verbose_name='Объект испытания'),
        ),
    ]
