# Generated by Django 3.0.6 on 2020-06-05 09:40

import calculatedtrials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatedtrials', '0004_calculated_testers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculated',
            name='data_calculated',
            field=models.DateField(db_index=True, help_text='Введите дату по данному формату: <em>DD.MM.YYYY</em>', verbose_name='Дата расчетного испытания'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='graph',
            field=models.ImageField(help_text="Разрешенные типы файлов: 'png', 'jpg', 'jpeg', 'gif', 'svg'", max_length=150, upload_to=calculatedtrials.models.content_graph_name, verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='settlementfile',
            name='settlementfile',
            field=models.FileField(help_text="Недопустимые типы файлов: 'png', 'jpg', 'jpeg', 'gif', 'svg'", max_length=150, upload_to=calculatedtrials.models.content_settlementfile_name, validators=[calculatedtrials.models.validate_report_extension], verbose_name='Расчетный файл'),
        ),
    ]
