# Generated by Django 3.0.6 on 2020-05-31 21:06

from django.db import migrations, models
import django.db.models.deletion
import stands.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_stand', models.CharField(max_length=40, unique=True, verbose_name='Название стенда')),
                ('slug_stand', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Стенд',
                'verbose_name_plural': 'Стенды',
            },
        ),
        migrations.CreateModel(
            name='DocumentStand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_document', models.CharField(max_length=100, unique=True, verbose_name='Название файла документа')),
                ('document', models.FileField(max_length=150, upload_to='stands/document/', verbose_name='Файл документа')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='stands.Stand', verbose_name='Стенд')),
            ],
            options={
                'verbose_name': 'Докуметация, схема стенда',
                'verbose_name_plural': 'Документации, схемы стенда',
            },
        ),
        migrations.CreateModel(
            name='ParameterStand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_parametr_stand', models.CharField(max_length=50, verbose_name='Название параметра')),
                ('value_parametr_stand', models.CharField(blank=True, max_length=20, validators=[stands.models.validate_number], verbose_name='Значение параметра')),
                ('measure_parametr_stand', models.CharField(blank=True, max_length=10, verbose_name='Единица измерения')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters_stand', to='stands.Stand', verbose_name='Стенд')),
            ],
            options={
                'verbose_name': 'Параметр стенда',
                'verbose_name_plural': 'Параметры стенда',
                'unique_together': {('stand', 'name_parametr_stand', 'value_parametr_stand', 'measure_parametr_stand')},
            },
        ),
    ]
